ci:
  skip: [pytest]

default_language_version:
  python: python3.12

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: ^(src/simulink)
    -   id: end-of-file-fixer
        exclude: ^(src/simulink)
    -   id: check-yaml
        exclude: ^(src/simulink)
    -   id: debug-statements
        exclude: ^(src/simulink)
    -   id: name-tests-test
        exclude: ^(src/simulink)
    -   id: requirements-txt-fixer
        exclude: ^(src/simulink)

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.10
  hooks:
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix]
      exclude: ^(src/simulink)

    - id: ruff-format
      types_or: [ python, pyi ]
      args: [ --line-length=88]
      exclude: ^(src/simulink)
