name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint • Type Check • Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install tools & deps
        run: |
          python -m pip install --upgrade pip
          # If you have dev extras, prefer: pip install -e ".[dev]"
          pip install ruff mypy pytest pytest-cov
          # Install your package in editable mode for tests
          pip install -e .

      - name: Ruff (format & lint)
        run: |
          ruff format --check .
          ruff check .

      - name: Mypy (static type check)
        run: |
          mypy src || mypy adaptive_oscillator

      - name: Pytest (with coverage)
        run: |
          pytest -q --cov=adaptive_oscillator --cov-report=term-missing --cov-fail-under=85
